version: "3"

services:
  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    expose:
      - "9090"
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
  alertmanager:
    restart: unless-stopped
    depends_on:
      - prometheus
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    expose:
      - "9093"
    ports:
      - 9093:9093
    extra_hosts:
      - "host.docker.internal:host-gateway"
  node-exporter:
    restart: unless-stopped
    depends_on:
      - prometheus
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - "9100"
    ports:
      - 9100:9100
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    restart: unless-stopped
    depends_on:
      - prometheus
    image: grafana/grafana-enterprise
    container_name: grafana
    expose:
      - "3000"
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
  api:
    restart: unless-stopped
    image: peppocola/ct-covid:v1
    container_name: api
    expose:
      - "5000"
    ports:
      - 5000:5000

