stages:
  data-ct:
    cmd: python src/preprocessing.py --size 224 224 data/raw data/ct
    deps:
    - src/preprocessing.py
    - data/raw
    outs:
    - data/ct
  train:
    cmd: python src/experiments.py
    deps:
    - data/ct
    - src/experiments.py
    params:
    - training.batch_size
    - training.data_path
    - training.epochs
    - training.lr
    - training.optimizer
    - training.patience
    - training.seed
    outs:
    - models/ct_net.pt
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/ct
    - models/ct_net.pt
    - src/evaluate.py
    metrics:
    - metrics/ct_net-clf-metrics.json:
        cache: false
    outs:
    - metrics/attentions
    params:
    - evaluation.data_path
    - evaluation.n_attention_maps
