apiVersion: apps/v1
kind: Deployment
metadata:
  name: ct-covid
  labels:
    app: ct-covd
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: ct-covid
  template:
    metadata:
      labels:
        app: ct-covid
    spec:
      containers:
        - name: ct-covid
          image: peppocola/ct-covid:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: 2Gi
              cpu: "0.25"
            limits:
              memory: 4Gi
              cpu: "0.5"

---
apiVersion: v1
kind: Service
metadata:
  name: ct-covid-service
  labels:
    app: ct-covid
spec:
  selector:
    app: ct-covid
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32000
